import db from './db.json';
import type { PageServerLoad } from './$types';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

export const load: PageServerLoad = async (request: any) => {
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        scopes: [
        'https://www.googleapis.com/auth/spreadsheets',
        ],
    });
    const doc = new GoogleSpreadsheet('1ieMwDsSDW-FZJZ_mE_-yuJiOFU3J2YFB7RQOW41Z7mc', serviceAccountAuth);

    try{
        await doc.loadInfo(); // loads document properties and worksheets
        console.log(doc.title);
    } catch (e) {
        console.error('Error: ', e.message);
    }
    return {"db": db};
};
